<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
	<NoWarn>8618;8602;CS8618;CS8602;CS8600;CS8604;CS8632</NoWarn>
	<Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Login\LoginResult.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Receta\Paciente\Response\" />
  </ItemGroup>

</Project>
