//namespace RMD.Models.CargaCatalogos
//{
//    public class ExcelCIM10Model
//    {
//        public string Consecutivo { get; set; }
//        public string Letra { get; set; }
//        public string CatalogKey { get; set; }
//        public string NoCaracteres { get; set; }
//        public string Nombre { get; set; }
//        public string Codigox { get; set; }
//        public string Lsex { get; set; }
//        public string Linf { get; set; }
//        public string Lsup { get; set; }
//        public string Trivial { get; set; }
//        public string Erradicado { get; set; }
//        public string NInter { get; set; }
//        public string Nin { get; set; }
//        public string NinmtObs { get; set; }
//        public string CodSitLesion { get; set; }
//        public string NoCbd { get; set; }
//        public string Cbd { get; set; }
//        public string NoAph { get; set; }
//        public string AfPrin { get; set; }
//        public string DiaSis { get; set; }
//        public string ClaveProgramaSis { get; set; }
//        public string CodComplemenMorbi { get; set; }
//        public string DiaFetal { get; set; }
//        public string DefFetalCm { get; set; }
//        public string DefFetalCbd { get; set; }
//        public string ClaveCapitulo { get; set; }
//        public string Capitulo { get; set; }
//        public string Lista1 { get; set; }
//        public string Grupo1 { get; set; }
//        public string Lista5 { get; set; }
//        public string RubricaType { get; set; }
//        public string YearModifi { get; set; }
//        public string YearAplicacion { get; set; }
//        public string Valid { get; set; }
//        public string PrinMorta { get; set; }
//        public string PrinMorbi { get; set; }
//        public string LmMorbi { get; set; }
//        public string LmMorta { get; set; }
//        public string Lgbd165 { get; set; }
//        public string Lomsbeck { get; set; }
//        public string Lgbd190 { get; set; }
//        public string NotDiaria { get; set; }
//        public string NotSemanal { get; set; }
//        public string SistemaEspecial { get; set; }
//        public string BirMm { get; set; }
//        public string CveCausaType { get; set; }
//        public string CausaType { get; set; }
//        public string EpiMorta { get; set; }
//        public string EdasEIrasEnM5 { get; set; }
//        public string CveMaternasSeedEpid { get; set; }
//        public string EpiMortaM5 { get; set; }
//        public string EpiMorbi { get; set; }
//        public string DefMaternas { get; set; }
//        public string EsCauses { get; set; }
//        public string NumCauses { get; set; }
//        public string EsSuiveMorta { get; set; }
//        public string EsSuiveMorb { get; set; }
//        public string EpiClave { get; set; }
//        public string EpiClaveDesc { get; set; }
//        public string EsSuiveNotin { get; set; }
//        public string EsSuiveEstEpi { get; set; }
//        public string EsSuiveEstBrote { get; set; }
//        public string Sinac { get; set; }
//        public string PrinSinac { get; set; }
//        public string PrinSinacGrupo { get; set; }
//        public string DescripcionSinacGrupo { get; set; }
//        public string PrinSinacSubgrupo { get; set; }
//        public string DescripcionSinacSubgrupo { get; set; }
//        public string Daga { get; set; }
//        public string Asterisco { get; set; }
//        public string PrinMm { get; set; }
//        public string PrinMmGrupo { get; set; }
//        public string DescripcionMmGrupo { get; set; }
//        public string PrinMmSubgrupo { get; set; }
//        public string DescripcionMmSubgrupo { get; set; }
//        public string CodAdiMort { get; set; }
//    }
//}
